apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: openshift-logging
  name: loki-s3-secret
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 5m
  secretStoreRef: 
    name: awssm-secretstore
    kind: ClusterSecretStore
  target: 
    name: loki-s3-secret
    creationPolicy: Owner
#  data: 
#  - secretKey: region
#    remoteRef:
#      key: openshift-logging-loki-secrets
#      property: region
#  - secretKey: 
#    remoteRef:
#      key: openshift-logging-loki-secrets
#      property: region
  dataFrom:
  - extract:
      key: openshift-logging-loki-secrets
