apiVersion: batch/v1
kind: Job
metadata:
  name: loki-operator-status-checker
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation 
spec:
  template:
    spec:
      containers:
      - name: wait-container
        image: registry.redhat.io/openshift4/ose-cli:latest 
        envFrom:
        - configMapRef:
            name: loki-operator-checker-config
        command:
        - /bin/sh
        - -c
        - >
#          while ! oc get csv -n openshift-logging -l operators.coreos.com/loki-operator.openshift-operators-redhat | grep Succeeded; do
          while ! oc get clusterserviceversion -n openshift-logging -o jsonpath='{range .items[*]}{.metadata.name} : {.status.phase}{"\n"}{end}'| grep loki-operator | grep Succeeded
          do
            sleep 10
          done
      restartPolicy: Never
      serviceAccountName: operator-checker
  backoffLimit: 4  
