apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  managementState: Managed
  size: 1x.extra-small
  storage:
    secret:
      name: loki-s3-secret
      type: s3
  storageClassName: gp3-csi
  tenants:
    mode: openshift-logging
