apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  name: stackrox-central-services
  namespace: stackrox
  annotations:
    argocd.argoproj.io/sync-wave: "3"
#    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
#    argocd.argoproj.io/hook: PostSync
spec:
  monitoring:
    openshift:
      enabled: true
  central:
    resources:
      limits:
        cpu: '1.5'
        memory: 4Gi
      requests:
        cpu: '4'
        memory: 8Gi
    nodeSelector:
      node-role.kubernetes.io/infra: ''
    exposure:
      loadBalancer:
        enabled: false
        port: 443
      nodePort:
        enabled: false
      route:
        enabled: true
    telemetry:
      enabled: true
    db:
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      isEnabled: Default
      persistence:
        persistentVolumeClaim:
          claimName: central-db
      resources:
        limits:
          cpu: '2'
          memory: 4Gi
        requests:
          cpu: '4'
          memory: 8Gi
    persistence:
      persistentVolumeClaim:
        claimName: stackrox-db
  egress:
    connectivityPolicy: Online
  scanner:
    analyzer:
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      scaling:
        autoScaling: Enabled
        maxReplicas: 5
        minReplicas: 2
        replicas: 3
