apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
resources:
# Syncwave: -1
- project.yaml
- operatorgroup.yaml

# Syncwave: 0
- acs-operator-checker-configmap.yaml
- subscription.yaml
- serviceaccount.yaml

# Syncwave: 1
- acs-operator-status-checker-job.yaml

# PostSync
- central.yaml
