apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhacs
  namespace: rhacs-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  targetNamespaces:
  - rhacs-operator
