---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-checker
  namespace: rhacs-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: operator-check-rolebinding
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: operator-checker
  namespace: rhacs-operator
